### ISSUE TITLE
Can't change City

### ISSUE THREAD

**Issue by hronek** [Fraasi/Saeae#1]
I can't change my city to "Písek". (It is in Czech Republic, South Bohemia - https://openweathermap.org/city/3068293)
Can You fix It? Or add support for put number of citi from opeanweathermap?

**Comment by Fraasi** [comment]
Sorry for the delay. Somehow i didnt get a notice of these issues and didnt see them. I have some plans to upgrade this app at some point. I will try to see and fix this as well, when i get to it that is... Hopefully in the next couple of weeks.

**Comment by Fraasi** [comment]
Openweathermap doesn't support that Czech í, so that doesn't find any city. Pisek works, but gets some other city from us, weird.   
Adding support for the city number is a good idea. I will do that in the next update.

edit:  
Holy weather octocat. Apparently there's more cities called pisek, so openweathemap picks one with who knows what algorithm.  
If you write 'pisek, cz' in the change city input, it works! Seems you need the country code for some cities to find the right city.

**Comment by Fraasi** [comment]
Closing this as latest release (v0.7.0) fixes this problem. Also readme instructions are much clearer on this now, https://github.com/Fraasi/Saeae/releases
